### ISSUE TITLE
Visuales 20160808

### ISSUE THREAD

**Issue by cristinamur** [primerproyecto/krismur2#4]
Juan,

Dejo estos visuales con la idea de que veas la home y el menú abierto y cerrado :

- Home Desktop   - Ver Menú cerrado
- Artwork (working progress) - Ver Menú abierto

Voy a seguir trabajando, pero para que veas por donde voy.

Como no me deja subir PSD, lo subo a una carpeta Drive:

https://drive.google.com/open?id=0B3bh0lLGqCgUaE1GV0tXOFNNakE

**Comment by primerproyecto** [comment]
Ok ...yo los voy colgando en la carpeta mocks del repositorio.
