### ISSUE TITLE
Imagenes - iconos en formato svg

### ISSUE THREAD

**Issue by primerproyecto** [primerproyecto/krismur2#6]
Para el logo, la cruz, las flechas, los elementos del menu, la imagen del artist statement y la de contacto, sería bueno utilizar imágenes en formato **svg** en lugar de png o jpg. Se renderiza mucho mejor y la mayoría de navegadores decentes actuales los leen (para los que no, utilizaremos las que ahora hay).

**Comment by cristinamur** [comment]
Si, lo había pensado  también. Los hago.  La ilustración del artist statement y la de contacto, nos los veo en **svg**, porque mas que iconos son ilustraciones, y no van a quedar bien vectorizadas. Para lo demás si lo veo.

**Comment by primerproyecto** [comment]
ok ..no se porque me da que sabes tu más de este formato que yo. 
Ok ...todo lo que veas que mejora en este formato ..pásamelo.
